---
name: cam-action
description: 'Run full cycle with one repository'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: docker
  image: Dockerfile
  entrypoint: /bin/bash
  args:
    - '--login'
    - '-c'
    - 'rvm default 3.2.2 && source /usr/local/rvm/scripts/rvm && ruby -v && bundle update && bundle exec rake'

