---
name: cam-action
description: 'Run full cycle with one repository'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: docker
  image: Dockerfile
  entrypoint: /bin/bash
  args:
    - 'ruby -v && bundle update && bundle exec rake'

